export const i18nMessages = {
  "en-US": {
    project: {
      name: "Werel",
    },
    account: {
      greeting: "Hello, {name}",
      your_credentials: "Your credentials",
      login: "Login",
      password: "Password",
      login_action: "Log-in",
      signon_action: "Sign-on",
    },
    ecosystem: {
      new_name: "New",
      remove: "Remove",
      list_header: "Ecosystems",
      dimensions_header: "Dimensions",
      equipment_header: "Equipment",
      water_params_header: "Water parameters",
      fish_list: "Fish",
      plants_list: "Plants",
      parameters: "Parameters",
      please_select: "Please select or create an ecosystem",
      volume_param: "{volume} L",
      actual_volume: "Actual volume: {volume}l",
      fish: {
        add_header: "Add fish",
        empty: "Add fish",
      },
      plants: {
        add_header: "Add plants",
        empty: "Add plants",
      },
      fields: {
        name: "Name",
        width: "Width",
        height: "Height",
        length: "Length",
        dim_suffix: "cm",
        volume: {
          hint: "Volume calculated based on the dimensions. Manually enter the volume if required",
        },
        filter_flow: "Filter flow",
        filter_flow_suffix: "liters/hour",
        heater_power: "Heater power",
        heater_suffix: "watts",
        lighting_power: "Lighting power",
        lighting_suffix: "lux",
        ph: "ph",
        gh: "gh",
        kh: "kh",
      },
      analysis: {
        not_available: "Not enough data for the analysis",
        your_progress: "Your progress",
        show_analysis: "Show analysis",
      },
    },
    fish: {
      add_action: "Add",
      more_info: "More info",
      search: "Search",
    },
    plants: {
      add_action: "Add",
      more_info: "More info",
      search: "Search",
    },
  },
  "ru-RU": {
    project: {
      name: "Werel",
    },
    account: {
      greeting: "Здравствуйте, {name}",
      your_credentials: "Ваш логин и пароль",
      login: "Логин",
      password: "Пароль",
      login_action: "Войти",
      signon_action: "Зарегистрироваться",
    },
    ecosystem: {
      new_name: "Новая",
      remove: "Удалить",
      list_header: "Экосистемы",
      dimensions_header: "Размеры",
      equipment_header: "Оборудование",
      water_params_header: "Параметры воды",
      fish_list: "Рыбки",
      plants_list: "Растения",
      parameters: "Параметры",
      please_select: "Выберите или создайте экосистему",
      volume_param: "{volume} л",
      actual_volume: "Реальный объем: {volume}л",
      add_fish_header: "Добавить рыбку",
      add_plants_header: "Добавить растения",
      fish: {
        add_header: "Добавить рыбку",
        empty: "Добавьте рыбку",
      },
      plants: {
        add_header: "Добавить растения",
        empty: "Добавьте растения",
      },
      fields: {
        name: "Название",
        width: "Ширина",
        height: "Высота",
        length: "Длина",
        dim_suffix: "см",
        volume: {
          hint: "Объем посчитан исходя из размеров аквариума. Если требуется - введите объем вручную",
        },
        filter_flow: "Мощность фильтра",
        filter_flow_suffix: "литров/час",
        heater_power: "Мощность нагревателя",
        heater_suffix: "ватт",
        lighting_power: "Мощность света",
        lighting_suffix: "lux",
        ph: "ph",
        gh: "gh",
        kh: "kh",
      },
      analysis: {
        not_available: "Недостаточно данных для анализа",
        your_progress: "Ваш прогресс",
        show_analysis: "Показать результаты анализа",
      },
    },
    fish: {
      add_action: "Добавить",
      more_info: "Информация",
      search: "Искать",
    },
    plants: {
      add_action: "Добавить",
      more_info: "Информация",
      search: "Искать",
    },
  },
};
