name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Build tests docker image
        id: build-for-tests
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          target: tester
          tags: arbuga/tests:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Tests
        run: docker run --rm -v ${{ github.workspace }}/tests:/build/output arbuga/tests:latest

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Vitests Tests
          path: tests/tests.xml
          reporter: jest-junit